name: freddiekemp
favicon: null
layout_spectrum: 0.9676347747445107
typography_spectrum: 0.4134365781210363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25822061276994646
  lightness: 0.6261341602075845
  saturation: 0.17961436952464283
  rhythmicContrast: 0.5623114232439548
purpose: []
